/*
 * Generates db/migration/V2__seed.sql from the legacy Coworkee JSON seeds.
 *
 * Determinism (PLAN 2.4): the legacy server/utils/data.js assigned office /
 * organization / manager / action-recipient RANDOMLY at boot. For reproducible
 * data + stable tests we assign them by a fixed modulo rule instead.
 *
 *   person[i].office        = offices[i % offices.length]
 *   person[i].organization  = organizations[i % organizations.length]
 *   organization[j].manager = people[j % people.length]
 *   action[k].recipient     = people[k % people.length]   (k = global action index)
 *
 * Dropped fields: password (ADR-004), gender, picture_gender, picture_index, index.
 * action.subject is precomputed from the recipient (legacy Action.subject).
 */
'use strict';
const fs = require('fs');
const path = require('path');

const dataDir = path.resolve(__dirname, '../../server/data');
const offices = require(path.join(dataDir, 'Offices.json'));
const organizations = require(path.join(dataDir, 'Organizations.json'));
const people = require(path.join(dataDir, 'People.json'));

function q(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return "'" + String(v).replace(/'/g, "''") + "'";
}
function num(v) {
  return v === null || v === undefined ? 'NULL' : Number(v);
}

// legacy Action.subject(type, recipient)
function actionSubject(type, r) {
  switch (type) {
    case 'phone':
      return r.phone + (r.extension ? ':' + r.extension : '');
    case 'profile':
      return r.username;
    case 'email':
    case 'linkedin':
    case 'skype':
      return r[type];
    default:
      return null;
  }
}

const lines = [];
lines.push('-- Auto-generated by scripts/generate-seed.js. Do not edit by hand.');
lines.push('-- Deterministic port of the legacy random seed (PLAN 2.4).');
lines.push('');

// Offices
lines.push('insert into offices (id, name, address, postcode, region, city, country, latitude, longitude) values');
lines.push(
  offices
    .map((o) => {
      const loc = o.location || {};
      return `  (${q(o.id)}, ${q(o.name)}, ${q(o.address)}, ${q(o.postcode)}, ${q(o.region)}, ${q(o.city)}, ${q(o.country)}, ${num(loc.latitude)}, ${num(loc.longitude)})`;
    })
    .join(',\n') + ';'
);
lines.push('');

// Organizations (manager_id set after people exist, so insert null then update)
lines.push('insert into organizations (id, name) values');
lines.push(organizations.map((o) => `  (${q(o.id)}, ${q(o.name)})`).join(',\n') + ';');
lines.push('');

// People
lines.push(
  'insert into people (id, email, username, firstname, lastname, title, phone, extension, skype, linkedin, picture, birthday, started, ended, office_id, organization_id) values'
);
lines.push(
  people
    .map((p, i) => {
      const office = offices[i % offices.length];
      const org = organizations[i % organizations.length];
      return `  (${q(p.id)}, ${q(p.email)}, ${q(p.username)}, ${q(p.firstname)}, ${q(p.lastname)}, ${q(p.title)}, ${q(p.phone)}, ${q(p.extension)}, ${q(p.skype)}, ${q(p.linkedin)}, ${q(p.picture)}, ${q(p.birthday)}, ${q(p.started)}, ${q(p.ended)}, ${q(office.id)}, ${q(org.id)})`;
    })
    .join(',\n') + ';'
);
lines.push('');

// Organization managers
organizations.forEach((o, j) => {
  const manager = people[j % people.length];
  lines.push(`update organizations set manager_id = ${q(manager.id)} where id = ${q(o.id)};`);
});
lines.push('');

// Actions (flatten embedded, assign recipient deterministically)
const actionRows = [];
let k = 0;
people.forEach((p) => {
  (p.actions || []).forEach((a) => {
    const recipient = people[k % people.length];
    const subject = actionSubject(a.type, recipient);
    actionRows.push(
      `  (${q(a.id)}, ${q(a.type)}, ${q(subject)}, ${q(a.created)}, ${q(recipient.id)})`
    );
    k++;
  });
});
lines.push(`-- ${actionRows.length} actions`);
lines.push('insert into actions (id, type, subject, created, recipient_id) values');
lines.push(actionRows.join(',\n') + ';');
lines.push('');

const out = path.resolve(__dirname, '../src/main/resources/db/migration/V2__seed.sql');
fs.writeFileSync(out, lines.join('\n'), 'utf8');
console.log(
  `Wrote ${out}\n  offices=${offices.length} organizations=${organizations.length} people=${people.length} actions=${actionRows.length}`
);
